datadog:
  apiKeyExistingSecret: datadog-secret
  clusterName: otel-mcp-test
  site: datadoghq.com
  collectEvents: true
  networkMonitoring:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  orchestratorExplorer:
    enabled: true
  tags:
    - env:dev
clusterAgent:
  enabled: true
  rbac: 
    create: true
