kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "demo-otel-cluster"
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    tags:
      - "env:dev"
  features:
    
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: "4317" # default port for OpenTelemetry gRPC receiver.
          hostPort: "4317"
          name: otel-grpc
        - containerPort: "4318" # default port for OpenTelemetry HTTP receiver
          hostPort: "4318"
          name: otel-http


datadog:
  apiKeyExistingSecret: datadog-secret
  clusterName: otel-mcp-test
  site: datadoghq.com
  collectEvents: true
  apm:
    portEnabled: true
    peer_tags_aggregation: true
    compute_stats_by_span_kind: true
    peer_service_aggregation: true
  networkMonitoring:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  orchestratorExplorer:
    enabled: true
  tags:
    - env:dev
otelCollector:
  enabled: true
  ports:
    - containerPort: "4317" # default port for OpenTelemetry gRPC receiver.
      hostPort: "4317"
      name: otel-grpc
    - containerPort: "4318" # default port for OpenTelemetry HTTP receiver
      hostPort: "4318"
      name: otel-http
clusterAgent:
  enabled: true
  rbac: 
    create: true
